// <auto-generated />
namespace YenidenDeneme.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class duz_context : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(duz_context));
        
        string IMigrationMetadata.Id
        {
            get { return "202510181322043_duz_context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
